name: Automated Release

on:
  push:
    branches:
      - main
      - hotfix/release

jobs:
  create_release:
    env:
      CGO_ENABLED: "1"
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxtst-dev libpng-dev xorg-dev gcc
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'
      - name: Build linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o stay-alive-linux-amd64 ./...
      - name: Build linux arm64
        run: GOOS=linux GOARCH=arm64 go build -o stay-alive-linux-arm64 ./...
      - name: Build linux arm
        run: GOOS=linux GOARCH=arm go build -o stay-alive-linux-arm ./...
      - name: Build windows amd64
        run: GOOS=windows GOARCH=amd64 go build -o stay-alive-windows-amd64 ./...
      - name: Build darwin amd64
        run: GOOS=darwin GOARCH=amd64 go build -o stay-alive-darwin-amd64 ./...
      - name: Build darwin arm64
        run: GOOS=darwin GOARCH=arm64 go build -o stay-alive-darwin-arm64 ./...
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ridedott/release-me-action@master
        with:
          release-assets: |
            ./stay-alive*
